version: '3'

networks:
  app:
    driver: bridge

services:
  app:
    image: node:14-alpine
    restart: always
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 80:${APP_PORT}
    depends_on:
      - db
    entrypoint: ./.docker/entrypoint.sh
    networks:
      - app


  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./.docker/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    networks:
      - app